### ISSUE TITLE
Chat message parsed before UltimateChat changes

### ISSUE THREAD

**Issue by XakepSDK** [Eufranio/MagiBridge#103]
I'm writing in chat message:
`aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa`
and in game i see only `aaa`, if i send
`aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaas`, in game i see `aaas`, but magibridge sends full, untransformed message in discord.

**Comment by Eufranio** [comment]
There are two events in UltimateChat: pre and post formatting. I can only work with the `pre` event, because it gives me the proper message with no formatting, so users are able to format how they want it displayed via MagiBridge, with custom prefixes and etc. The `post` event doesn't have a proper message, instead it has the message that will be sent to every user, with colors, prefixes, placeholders and everything else, that I cannot use.

So, this fix is not on my end, for now. It'd be nice if UChat fired an event after parsing the message with the spam filters, but I have no knowledge on it's internals and if this would be feasible. Sorry.
