### ISSUE TITLE
discord cant see MC messages

### ISSUE THREAD

**Issue by ZaosDaOne** [Eufranio/MagiBridge#83]
in mc they can see discord messages but discord cant see mc messages unless using /mb i have luckperms and nucleus

**Comment by Cebtenzzre** [comment]
@ZaosDaOne Try making sure you have webhooks set up right (the perms are correct for the bot's role on Discord), and that there are no error messages coming from MagiBridge in the server console/log.

The only other case I've seen in which that happened was that someone was using an old version of MagiBridge, and BungeeCord, without Nucleus's chat module, or uChat.  It was a double whammy:
- They had to get a newer version of MagiBridge that supported vanilla chat integration
- And they needed to set  "passToClientServer" to true in BungeeChat so that the server (and thusly MagiBridge) could see the messages

IIRC they needed NoChat as well to prevent double-echoing the chat to clients.
